### ISSUE TITLE
Panic when getting ips for cao deployed cluster

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/cbdinocluster#41]
And for a bonus, no --version.  :)

I might not expect this to be useful, but I didn't expect it to panic.

````
➜  cbdinocluster git:(master) ✗ ./cbdinocluster ps
2024-03-20T18:28:32.885-0700	INFO	logger initialized
2024-03-20T18:28:32.886-0700	INFO	identified available deployers	{"deployers": ["cao", "docker"]}
Clusters:
  d88c46b7008d45d8ad808bd4435b1dc3 [State: available, Timeout: none, Deployer: cao]
➜  cbdinocluster git:(master) ✗ ./cbdinocluster ip d88c
2024-03-20T18:28:39.770-0700	INFO	logger initialized
2024-03-20T18:28:39.770-0700	INFO	attempting to identify cluster	{"input": "d88c"}
2024-03-20T18:28:39.771-0700	INFO	identified available deployers	{"deployers": ["docker", "cao"]}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/couchbaselabs/cbdinocluster/cmd.glob..func28(0x14000229200?, {0x14000651a80, 0x1, 0x1019d3303?})
	/Users/ingenthr/src/cbdinocluster/cmd/ip.go:24 +0x118
github.com/spf13/cobra.(*Command).execute(0x102e9b860, {0x14000651a50, 0x1, 0x1})
	/Users/ingenthr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x102e96ac0)
	/Users/ingenthr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ingenthr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/couchbaselabs/cbdinocluster/cmd.Execute()
	/Users/ingenthr/src/cbdinocluster/cmd/root.go:16 +0x24
main.main()
	/Users/ingenthr/src/cbdinocluster/main.go:8 +0x1c
➜  cbdinocluster git:(master) ✗ ./cbdinocluster -v
provides tooling for quickly creating, modifying and destroying couchbase clusters.

Usage:
  cbdinocluster [command]

Available Commands:
  allocate          Allocates a cluster
  allow-list        Provides access to tools related to Couchbase Cloud allow lists
  buckets           Provides the ability to manipulate the buckets of a system
  certificates      Provides access to tools related to Couchbase Cloud certificates
  chaos             Provides chaos tools for the system
  cleanup           Cleans up any expired resources for a deployer
  collect-logs      Gets a connection string to connect to the cluster
  collections       Provides the ability to manipulate the collections of a system
  completion        Generate the autocompletion script for the specified shell
  config            Provides access to configuration options for dinocluster
  connstr           Gets a connection string to connect to the cluster
  def               Provides access to definition manipulation tools
  get-definition    Gets the cluster definition for a cluster
  help              Help about any command
  images            Provides the ability to list/search server version images.
  init              Initializes the tool
  ip                Gets the IP of a node in the cluster
  list              Lists all clusters
  mgmt              Gets an address to management the cluster
  modify            Modifies an existing cluster
  private-endpoints Provides access to tools related to Couchbase Cloud Private Endpoints
  query             Executes a query against the cluster
  refresh           Refreshes the expiry for a cluster
  remove            Removes a cluster
  remove-all        Removes all running clusters
  tools             Provides access to tools for testing various dinocluster functionality
  users             Provides the ability to manipulate the users of a system

Flags:
  -h, --help      help for cbdinocluster
      --json      Turns on JSON output for supported commands
  -v, --verbose   Turns on verbose logging

Use "cbdinocluster [command] --help" for more information about a command.
➜  cbdinocluster git:(master) ✗ ./cbdinocluster --version
Error: unknown flag: --version
Usage:
  cbdinocluster [command]

Available Commands:
  allocate          Allocates a cluster
  allow-list        Provides access to tools related to Couchbase Cloud allow lists
  buckets           Provides the ability to manipulate the buckets of a system
  certificates      Provides access to tools related to Couchbase Cloud certificates
  chaos             Provides chaos tools for the system
  cleanup           Cleans up any expired resources for a deployer
  collect-logs      Gets a connection string to connect to the cluster
  collections       Provides the ability to manipulate the collections of a system
  completion        Generate the autocompletion script for the specified shell
  config            Provides access to configuration options for dinocluster
  connstr           Gets a connection string to connect to the cluster
  def               Provides access to definition manipulation tools
  get-definition    Gets the cluster definition for a cluster
  help              Help about any command
  images            Provides the ability to list/search server version images.
  init              Initializes the tool
  ip                Gets the IP of a node in the cluster
  list              Lists all clusters
  mgmt              Gets an address to management the cluster
  modify            Modifies an existing cluster
  private-endpoints Provides access to tools related to Couchbase Cloud Private Endpoints
  query             Executes a query against the cluster
  refresh           Refreshes the expiry for a cluster
  remove            Removes a cluster
  remove-all        Removes all running clusters
  tools             Provides access to tools for testing various dinocluster functionality
  users             Provides the ability to manipulate the users of a system

Flags:
  -h, --help      help for cbdinocluster
      --json      Turns on JSON output for supported commands
  -v, --verbose   Turns on verbose logging

Use "cbdinocluster [command] --help" for more information about a command.

2024/03/20 18:29:03 failed to initialize command line parser: unknown flag: --version
➜  cbdinocluster git:(master) ✗ ./cbdinocluster version
Error: unknown command "version" for "cbdinocluster"
Run 'cbdinocluster --help' for usage.
2024/03/20 18:29:14 failed to initialize command line parser: unknown command "version" for "cbdinocluster"
➜  cbdinocluster git:(master) ✗ git describe
fatal: No annotated tags can describe '72dd5c6f540ea82deed49217398708681dfc715e'.
However, there were unannotated tags: try --tags.
➜  cbdinocluster git:(master) ✗ git describe --tags
v0.0.25
````

**Comment by brett19** [comment]
Looks like the ips command incorrectly assumes all deployers are able to provide per-node information, but only the docker deployer actually can, leading to a panic when we index into the list.

Version information is annoyingly difficult to provide so it's not been added yet, but is tracked through https://github.com/couchbaselabs/cbdinocluster/issues/17.
